"use client";

import { SURVIVOR_RARITY_DEFINITIONS } from "./survivor-engine";
import { CONTINUITY_EXPERTISE_PRESENTATION } from "./continuity-expertise";
import type { ResearchInputId } from "./research-engine";

export type ManualPageId =
  | "deck"
  | "engineering"
  | "research"
  | "population"
  | "expeditions"
  | "defense"
  | "armory"
  | "settlement";

export type ManualTopicId = ManualPageId | "salvage" | ResearchInputId;

type ManualStep = {
  title: string;
  detail: string;
};

type ManualSource = {
  label: string;
  detail: string;
};

export type ManualTopic = {
  id: ManualTopicId;
  label: string;
  category: string;
  title: string;
  summary: string;
  steps: readonly ManualStep[];
  sources?: readonly ManualSource[];
  tip?: string;
};

export const MANUAL_PAGE_LABELS: Record<ManualPageId, string> = {
  deck: "Ark",
  engineering: "Foundry",
  research: "Research",
  population: "Crew",
  expeditions: "Expeditions",
  defense: "Defense",
  armory: "Armory",
  settlement: "Continuity",
};

export const MANUAL_TOPICS: Record<ManualTopicId, ManualTopic> = {
  deck: {
    id: "deck",
    label: "Ark",
    category: "Page guide // command deck",
    title: "Wake the Ark one system at a time",
    summary:
      "The Ark is your visual command deck. Tune its Core, watch the ship awaken, and enter each room only after the current directive brings it online.",
    steps: [
      { title: "Tune the Core", detail: "Click the Axiom Chamber to gain Flux and one Calibration Data per tune." },
      { title: "Follow the active directive", detail: "The strip above the Ark always names the next useful action and shows its progress." },
      { title: "Enter awakened rooms", detail: "Foundry, Research, Crew, and Continuity appear progressively instead of arriving all at once." },
    ],
    sources: [
      { label: "Flux", detail: "Core tunes and Foundry machines create the energy used by almost every early action." },
      { label: "Salvage", detail: "Slowly recovered by the Ark, improved by crew assignments, and awarded by planetary work." },
      { label: "Axioms", detail: "Permanent laws earned by Recalibration. They survive the cycle reset." },
    ],
    tip: "Nothing on the Ark expires. If a room is dark, the active directive will eventually explain how to wake it.",
  },
  engineering: {
    id: "engineering",
    label: "Foundry",
    category: "Page guide // fabrication floor",
    title: "Build the machine that builds the next machine",
    summary:
      "The Foundry owns fabrication, Planetfall directives, Core Protocols, automation, Recalibration, and statistics. Core tuning stays on the Ark.",
    steps: [
      { title: "Buy the first mechanism", detail: "Every machine produces Flux directly - each tier simply produces far more per unit. Your Flux/sec only changes when you buy something; nothing grows on its own." },
      { title: "Keep adjacent tiers balanced", detail: "Groups of 15 across neighboring tiers create Resonance and improve the whole chain." },
      { title: "Complete Planetfall phases", detail: "Directives award Salvage and crew experience while progressively revealing the Foundry's deeper systems." },
      { title: "Recalibrate when worthwhile", detail: "Recalibration resets the current assembly but awards permanent Axioms and preserves people, research, and restored worlds." },
    ],
    sources: [
      { label: "Machine multiplier", detail: "Comes from purchases, milestones, Resonance, research, world effects, and permanent upgrades." },
      { label: "Balanced links", detail: "Created when neighboring tiers hold enough matched groups of 15." },
      { label: "Lifetime Axioms", detail: "Your permanent total across every Recalibration cycle." },
    ],
    tip: "You do not need to buy everything immediately. The active directive is the safest guide to the next efficient target.",
  },
  research: {
    id: "research",
    label: "Research",
    category: "Page guide // analysis core",
    title: "Move evidence from the Ark into a working route",
    summary:
      "Research resources first collect in Ark Supply. They do nothing inside a project until you transfer them into the Lattice and connect an accepted route.",
    steps: [
      { title: "Select a program", detail: "Choose an available project. Its required evidence reservoirs begin glowing." },
      { title: "Transfer Ark Supply", detail: "Press +25 beside each required resource to move it into Lattice inventory." },
      { title: "Route the evidence", detail: "Leave AXIOM Assist enabled at first; it connects compatible sources and processors automatically." },
      { title: "Staff the Analysis Core", detail: "Researchers and Technicians increase available staffing. Projects continue while you are away." },
    ],
    sources: [
      { label: "Ark Supply", detail: "The reserve generated by Core work, machines, survivors, worlds, crises, and Recalibrations." },
      { label: "Lattice", detail: "The smaller inventory already transferred into the Analysis Core and available to active projects." },
      { label: "Throughput", detail: "Limited by connected routes, processor compatibility, power, crew, and available evidence." },
    ],
    tip: "If Ark Supply is above zero but Lattice reads zero, press the +25 transfer button. That is the most common stalled-research cause.",
  },
  population: {
    id: "population",
    label: "Crew",
    category: "Page guide // human continuity",
    title: "Make the Ark safe, answer signals, then shape the crew",
    summary:
      "Rescue groups never expire. Build safe capacity with Salvage, answer the SOS signal when ready, then assign specialists or train adaptable civilians.",
    steps: [
      { title: "Build quarters and expand life support", detail: "Crew quarters come from Habitation Ring sections built with Flux (assigned engineers speed construction). Atmosphere, water, nutrition, and medical capacity expand with Salvage. Both must cover the incoming group." },
      { title: "Activate the SOS beacon", detail: "Once the Ark reaches a planetary orbit, the beacon finds a persistent group after 90 seconds." },
      { title: "Dispatch the rescue shuttle", detail: "Spend the listed Salvage to bring the entire group aboard. Each person also brings Biological Samples and Cultural Records." },
      { title: "Assign or train", detail: "Assigned specialists earn profession XP offline. Standard profiles learn at ×1.00, Notable ×1.25, Exceptional ×1.60, and Anomalous ×2.00." },
    ],
    sources: [
      { label: "Profile rarity", detail: "Colors describe how scarce a recruit's aptitude, adaptability, trait, and archive combination is—not their human worth. Rarity accelerates training and job XP and sets profession capacity (Standard 1, Notable 2, Exceptional 3, Anomalous unlimited)." },
      { label: "Profession levels", detail: "Levels come from XP and create Continuity expertise. Rarity never multiplies that expertise directly." },
      { label: "Training slots", detail: "One program can run per slot. Slots grow with population (+1 per 20 people) and the Adaptive Instruction and Clinical Commons research projects, up to 12." },
      { label: "Civilians", detail: "Highly adaptable recruits who can be trained around the exact needs of a future settlement." },
      { label: "Specialists", detail: "Arrive ready for a profession and improve through assigned work. Notable-or-better specialists can cross-train additional professions." },
      { label: "Expeditions & health", detail: "The Expedition Bay always projects the outcome before launch. Setbacks send crew home wounded (below 40 health = RECOVERING); a projected DISTRESS would strand them at the site. Stranded crews are stable forever - send a rescue party (it can never strand itself) or, only by explicit choice, abandon them to the memorial wall. Nothing in the game kills crew automatically." },
      { label: "Team Alpha", detail: "Appoint a crew leader plus up to three officers from any personnel file. Their combined continuity expertise becomes a Command Rating that boosts crew-wide training and job XP (capped). With a leader appointed, set a Training Doctrine (a lean): empty training slots auto-fill with your best IDLE crew for that profession - it never cancels manual programs or pulls anyone off a station. Officers keep their jobs and can still deploy or found colonies; their contribution simply pauses while they are away or recovering." },
    ],
    tip: "Roster order stays chronological. Color and visible labels identify rare profiles without hiding anyone or changing rescue priority.",
  },
  defense: {
    id: "defense",
    label: "Defense",
    category: "Page guide // threat operations",
    title: "Prepare the Ark, then let it defend itself",
    summary:
      "From Cinder onward, ash storms sweep the Ark's orbit. Build installations, choose a standing doctrine, and every storm resolves automatically - online or offline. Nothing here can kill crew or erase progress.",
    steps: [
      { title: "Build installations", detail: "Shield Arrays carry readiness; Repair Drones speed recovery; the Early-Warning Relay extends storm forecasts; Point-Defense matters most against future hostile contacts." },
      { title: "Assign defenders", detail: "Assigned Soldiers raise readiness and interception, Engineers add readiness and repair speed, Navigators extend forecast lead time." },
      { title: "Choose a doctrine", detail: "Defend is the safe default. Evade nearly eliminates risk for little reward. Intercept risks damage for extra Salvage and Engineering Models. Observe accepts small risk to gather Calibration Data and Null Traces." },
      { title: "Read the log", detail: "Every resolution is recorded with its severity, readiness, margin, and outcome, so offline results are always explainable." },
    ],
    sources: [
      { label: "Worst case", detail: "A battered outcome temporarily reduces production by at most 25% while repairs run (six hours maximum, faster with drones and engineers). Damage never stacks deeper." },
      { label: "Null Traces", detail: "The Observe doctrine is the active way to gather Null Traces from Cinder onward." },
    ],
    tip: "Storms never arrive unannounced faster than 15 minutes, and the first storm is always mild.",
  },
  expeditions: {
    id: "expeditions",
    label: "Expeditions",
    category: "Page guide // expedition command",
    title: "Read the projection, pick the crew, launch",
    summary:
      "From Cinder onward, crews of 2-4 fly surface missions for salvage, schematics, Null Traces, XP, and planetary certification. The bay always projects the outcome before launch - you are never ambushed.",
    steps: [
      { title: "Pick a destination", detail: "Planetary Surveys certify the world for departure and are repeatable. Other sites carry bigger rewards and higher difficulty." },
      { title: "Build the crew", detail: "Each member adds their best profession level. Soldiers level 3+ add +2 strength, Researchers +1, Navigators 3+ shorten the trip. Gear from the Armory auto-equips." },
      { title: "Respect the projection", detail: "SUCCESS and LEAN are safe. SETBACK sends everyone home wounded. DISTRESS strands the party at the site - launching into either warning takes an extra confirm." },
      { title: "Handle distress calmly", detail: "Stranded crews are stable forever and the signal never expires. Send a rescue party (strength of difficulty-4 extracts cleanly; weaker parties take wounds but still bring everyone home), or - only by explicit choice - abandon them to the memorial wall." },
    ],
    sources: [
      { label: "Outcome bands", detail: "Success at strength >= difficulty; lean within 8 below; setback within 16; distress beyond that. Weapons add strength, armor absorbs wound damage." },
      { label: "XP", detail: "Members earn (60 + 6 x difficulty) XP to their profession, x1.5 when it matches the site's focus, scaled by outcome." },
    ],
    tip: "Missions resolve fully offline. A rescue mission can never strand itself - the only way to lose someone is the Abandon button.",
  },
  armory: {
    id: "armory",
    label: "Armory",
    category: "Page guide // expedition outfitting",
    title: "Forge the gear, and expeditions equip themselves",
    summary:
      "Weapons and armor are shared Ark stock. Research a tier in the Threat Operations branch, forge pieces with Flux and Engineering Models, and every expedition auto-equips the best gear each member is leveled to use.",
    steps: [
      { title: "Research a tier", detail: "Each weapon and armor tier is a Threat Operations research project. Tier 3 gear also costs Null Traces to forge." },
      { title: "Forge pieces", detail: "One piece outfits one expedition member. Four of each covers a full crew." },
      { title: "Check wield levels", detail: "A survivor's best professional level decides what they can carry: Pike 2 / Carbine 4 / Lance 6, Weave 1 / Shell 3 / Frame 5." },
      { title: "Repair after setbacks", detail: "Armor that absorbs a hit loses durability and eventually reads DAMAGED. Repairs cost 40% of the forge price." },
    ],
    sources: [
      { label: "Weapons", detail: "Add group strength per equipped member (+2/+4/+6 by tier) and never break." },
      { label: "Armor", detail: "Multiplies setback wound damage (×0.5/×0.35/×0.2 by tier) and limits the worst possible permanent injury." },
      { label: "Health", detail: "Wounded crew (below 40 health) recover at +2/hour, faster with assigned Doctors. Only expedition setbacks ever deal damage." },
    ],
    tip: "The armory survives Recalibration and travels between worlds. Gear you forge now protects every future crew.",
  },
  settlement: {
    id: "settlement",
    label: "Continuity",
    category: "Page guide // planetary continuity",
    title: "Leave only when a world can continue without the Ark",
    summary:
      "Continuity combines population, expertise, infrastructure, supplies, research, crisis response, and your chosen founders into one departure forecast.",
    steps: [
      { title: "Read the explicit deficits", detail: "Every unmet requirement names the direct fix and any research or equipment substitute." },
      { title: "Complete permanent world work", detail: "Infrastructure, stored supplies, and required research remain completed. Every crisis card lists its Foundry, infrastructure, research, and Flux prerequisites live." },
      { title: "Choose eligible founders", detail: "Select enough people, profession coverage, combined Expertise, and—on later worlds—the visible Profile Depth requirement." },
      { title: "Name and establish the settlement", detail: "Departure becomes available only when every requirement is met. There is no deadline." },
    ],
    sources: [
      { label: "Viability", detail: "A readable summary of how close the current world is to independent survival." },
      { label: "Expertise", detail: "Combined profession levels from selected founders. Open any requirement's ‘How this is counted’ row to see its formula and contributors." },
      { label: "Leadership", detail: "70% of Security level plus 40% of Navigator level, each rounded up. Even a level-one qualification contributes." },
      { label: "Profile Depth", detail: "Cinder requires 2 Notable-or-better founders; Nox requires 4 including 1 Exceptional; Vesper requires 6 including 3 Exceptional. Anomalous counts as Exceptional." },
      { label: "Substitutions", detail: "Research and fabricated equipment prevent unlucky recruitment from hard-locking a world." },
    ],
    tip: "Founders remain alive in the colony record after departure. The SOS array guarantees an Exceptional-or-better profile within five quality misses, so Profile Depth can never become a permanent luck wall.",
  },
  salvage: {
    id: "salvage",
    label: "Salvage",
    category: "Resource guide // recovery stores",
    title: "Salvage is the bridge between an empty Ark and its first crew",
    summary:
      "Salvage pays for life-support capacity, rescue shuttles, and later Foundry upgrades. It recovers automatically and never requires a timer challenge.",
    steps: [
      { title: "Wait for base recovery", detail: "The Ark begins with 35 Salvage and automatically recovers 43.2 per hour, including offline time." },
      { title: "Assign recovery workers", detail: "Every assigned Fabricator or Technician adds 21.6 Salvage per hour." },
      { title: "Complete planetary work", detail: "Planetfall phase completions and stabilized worlds award extra Salvage caches." },
      { title: "Launch expeditions later", detail: "After enough worlds are secured, Expedition Bay routes return larger Salvage manifests." },
    ],
    sources: [
      { label: "Passive recovery", detail: "Always active, even with no crew aboard." },
      { label: "Crew recovery", detail: "Added by working assignments, not merely by owning a specialist." },
      { label: "Campaign caches", detail: "Awarded when Planetfall work advances and when a world is secured." },
    ],
    tip: "Early on, save enough Salvage to expand every life-support category and still pay the rescue signal's shuttle cost.",
  },
  "calibration-data": {
    id: "calibration-data",
    label: "Calibration Data",
    category: "Research input // CAL",
    title: "Record how the damaged Core responds",
    summary: "Calibration Data comes from operating and observing the Axiom Chamber.",
    steps: [
      { title: "Tune the Core", detail: "Every manual Core tune immediately adds 1 Calibration Data to Ark Supply." },
      { title: "Let instruments observe", detail: "The Ark also records 90 Calibration Data per hour passively." },
      { title: "Transfer it", detail: "Open Evidence Reservoirs and press +25 before a project can consume it." },
    ],
  },
  "engineering-models": {
    id: "engineering-models",
    label: "Engineering Models",
    category: "Research input // ENG",
    title: "Turn fabrication into repeatable system models",
    summary: "Engineering Models are created by building mechanisms and proving infrastructure designs.",
    steps: [
      { title: "Buy Foundry machines", detail: "Every machine purchase adds a small batch, with higher tiers producing slightly more." },
      { title: "Increase Flux production", detail: "Model generation rises passively with the strength of the active fabrication chain." },
      { title: "Complete infrastructure", detail: "Planetary infrastructure projects award larger model batches." },
    ],
  },
  "biological-samples": {
    id: "biological-samples",
    label: "Biological Samples",
    category: "Research input // BIO",
    title: "Biological evidence begins with rescued life",
    summary: "Biological Samples stay at zero until at least one survivor is aboard the Ark.",
    steps: [
      { title: "Rescue survivors", detail: "Each rescued person immediately adds 18 Biological Samples to Ark Supply." },
      { title: "Maintain a population", detail: "Every person aboard contributes another 10.8 Biological Samples per hour, including offline time." },
      { title: "Transfer it", detail: "Press +25 in Evidence Reservoirs to move Ark Supply into the Lattice." },
    ],
    tip: "No survivor is harmed or consumed. Samples represent non-destructive clinical and planetary observations.",
  },
  "cultural-records": {
    id: "cultural-records",
    label: "Cultural Records",
    category: "Research input // CUL",
    title: "Every rescued person brings memory the Ark did not possess",
    summary: "Cultural Records come from testimony, teaching material, and recovered civic knowledge.",
    steps: [
      { title: "Rescue survivors", detail: "Each rescued person immediately adds 22 Cultural Records to Ark Supply." },
      { title: "Let the archive grow", detail: "Every person aboard contributes another 14.4 Cultural Records per hour, including offline time." },
      { title: "Transfer it", detail: "Press +25 in Evidence Reservoirs to move Ark Supply into the Lattice." },
    ],
  },
  schematics: {
    id: "schematics",
    label: "Schematics",
    category: "Research input // SCH",
    title: "Designs the Ark cannot invent — only recover",
    summary:
      "Recovered Schematics fuel the Threat Operations research branch (weapons and armor tiers). Nothing aboard generates them: they arrive only with people and expeditions, which makes them one of the scarcest reservoirs in the game.",
    steps: [
      { title: "Answer SOS signals", detail: "Every rescued group carries schematics in its cargo manifest — richer on later worlds." },
      { title: "Fly expeditions", detail: "Every site pays schematics on return, scaled by the outcome. Surveys are the steady repeatable source." },
      { title: "Spend them on Threat Operations", detail: "Weapon and armor research tiers are priced mostly in schematics. Transfer them into the Lattice like any evidence reservoir." },
    ],
    tip: "Both sources are time-locked — scan cadence and mission clocks — so schematics can't be farmed by idling. Plan the branch around your rescue and expedition rhythm.",
  },
  "null-traces": {
    id: "null-traces",
    label: "Null Traces",
    category: "Research input // NUL",
    title: "Measure absences that should not leave evidence",
    summary: "Null Traces begin accumulating after Cold Wake as the Ark enters later worlds.",
    steps: [
      { title: "Advance beyond Cold Wake", detail: "Later worlds generate a small passive Null signal; deeper campaign progress strengthens it." },
      { title: "Resolve planetary crises", detail: "Each resolved crisis awards a larger batch of Null Traces." },
      { title: "Route carefully", detail: "Null projects often need specialized processors and reveal lore the bootstrap archive omitted." },
    ],
  },
  "axiom-proofs": {
    id: "axiom-proofs",
    label: "Axiom Proofs",
    category: "Research input // AXM",
    title: "Prove which laws survive a rebuilt universe",
    summary: "Axiom Proofs are the research evidence created by Recalibration and permanent physical laws.",
    steps: [
      { title: "Recalibrate", detail: "Every Axiom earned in a Recalibration immediately awards 8 Axiom Proofs." },
      { title: "Keep lifetime Axioms", detail: "Each lifetime Axiom continues producing a small passive proof signal." },
      { title: "Transfer it", detail: "Move Proofs from Ark Supply into the Lattice only when a selected project requires them." },
    ],
  },
};

const RESOURCE_TOPIC_IDS: readonly ManualTopicId[] = [
  "salvage",
  "calibration-data",
  "engineering-models",
  "biological-samples",
  "cultural-records",
  "schematics",
  "null-traces",
  "axiom-proofs",
];

export function HelpTrigger({
  label,
  onClick,
  withLabel = false,
}: {
  label: string;
  onClick: () => void;
  withLabel?: boolean;
}) {
  return (
    <button
      className={`context-help-trigger ${withLabel ? "with-label" : ""}`}
      type="button"
      aria-label={label}
      title={label}
      onClick={onClick}
    >
      <span aria-hidden="true">?</span>
      {withLabel ? <strong>Guide</strong> : null}
    </button>
  );
}

export function GameManualDialog({
  topicId,
  availablePages,
  onSelectTopic,
  onClose,
}: {
  topicId: ManualTopicId;
  availablePages: readonly ManualPageId[];
  onSelectTopic: (topicId: ManualTopicId) => void;
  onClose: () => void;
}) {
  const topic = MANUAL_TOPICS[topicId];
  const researchAvailable = availablePages.includes("research");

  return (
    <div className="manual-layer">
      <button className="modal-backdrop" type="button" aria-label="Close field manual" onClick={onClose} />
      <section className="game-manual" role="dialog" aria-modal="true" aria-labelledby="manual-title" aria-describedby="manual-summary">
        <header className="game-manual-header">
          <div>
            <p>AXIOM FIELD MANUAL // CONTEXT LINK</p>
            <h2 id="manual-title">{topic.title}</h2>
            <span id="manual-summary">{topic.summary}</span>
          </div>
          <button className="manual-close" type="button" autoFocus onClick={onClose}>Close</button>
        </header>

        <div className="game-manual-layout">
          <nav className="game-manual-index" aria-label="Unlocked page guides">
            <span>Unlocked pages</span>
            {availablePages.map((pageId) => (
              <button
                className={topicId === pageId ? "is-active" : ""}
                type="button"
                key={pageId}
                onClick={() => onSelectTopic(pageId)}
              >
                <i aria-hidden="true" />
                {MANUAL_PAGE_LABELS[pageId]}
              </button>
            ))}
            <span>Resource index</span>
            {RESOURCE_TOPIC_IDS.filter((resourceId) => resourceId === "salvage" || researchAvailable).map((resourceId) => (
              <button
                className={topicId === resourceId ? "is-active" : ""}
                type="button"
                key={resourceId}
                onClick={() => onSelectTopic(resourceId)}
              >
                <i aria-hidden="true" />
                {MANUAL_TOPICS[resourceId].label}
              </button>
            ))}
          </nav>

          <article className="game-manual-topic">
            <p className="game-manual-category">{topic.category}</p>
            <ol className="game-manual-steps">
              {topic.steps.map((step, index) => (
                <li key={step.title}>
                  <span>{String(index + 1).padStart(2, "0")}</span>
                  <div><strong>{step.title}</strong><p>{step.detail}</p></div>
                </li>
              ))}
            </ol>

            {topic.sources && (
              <section className="game-manual-sources" aria-label="Related concepts">
                <h3>What the readouts mean</h3>
                <div>
                  {topic.sources.map((source) => (
                    <article key={source.label}>
                      <strong>{source.label}</strong>
                      <p>{source.detail}</p>
                    </article>
                  ))}
                </div>
              </section>
            )}

            {topicId === "population" && (
              <section className="game-manual-rarity" aria-label="Profile rarity legend">
                <h3>Profile rarity colors</h3>
                <div>
                  {SURVIVOR_RARITY_DEFINITIONS.map((rarity) => (
                    <span className={`crew-rarity-${rarity.id}`} title={rarity.description} key={rarity.id}>
                      <i aria-hidden="true" />
                      <strong>{rarity.label} ×{rarity.learningMultiplier.toFixed(2)}</strong>
                    </span>
                  ))}
                </div>
              </section>
            )}

            {topicId === "settlement" && (
              <section className="game-manual-formulas" aria-label="Continuity expertise formulas">
                <h3>Exact Expertise formulas</h3>
                <div>
                  {Object.entries(CONTINUITY_EXPERTISE_PRESENTATION).map(([id, presentation]) => (
                    <article key={id}><strong>{presentation.label}</strong><p>{presentation.formula}</p></article>
                  ))}
                </div>
              </section>
            )}

            {topic.tip && <aside className="game-manual-tip"><span>AXIOM NOTE</span><p>{topic.tip}</p></aside>}
          </article>
        </div>
      </section>
    </div>
  );
}
